### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by xylobol** [gmpassos/docker_commander#1]
Hi! I'm looking to use this package in a few projects, but it's not updated for the new null safety in Dart. If you can give me any pointers as to where I can help with this, I'd be happy to send patches.

**Comment by gmpassos** [comment]
I will migrate to Null Safety in the next week.

**Comment by xylobol** [comment]
Sweet, thanks! Please let me know if there's any way I can help with this.

**Comment by gmpassos** [comment]
The project needs more unit tests. With more tests will be easier to validade the Null Safety migration.

**Comment by gmpassos** [comment]
The new version `2.0.0` is Null Safety compatible.
